### PR TITLE
Email sender branch

### PR DESCRIPTION
**Pull request by maklil**
Added the EmailSender.java 
the required jar : 
javax.mail.jar and activation.jar

please delete the folder "EmailSender" that contains 1 file "tocreatefolder", it was a mistake because i wanted to create this folder under "Model" to put the EmailSender.java inside it...

and do you need the other files ? ( in the folders of the project : src, out and .idea) ?

### CODE REVIEW

**Comment by akhial** [comment]
No you don't need to add the other folders but I don't understand what you mean by delete the folder?

**Comment by maklil** [comment]
My intention was to put my work on a folder called "EmailSender" inside Model, but instead, i created "EmailSender" (the folder) beside Model, and you know when you create a new folder you have to put a file inside it (which is in this case the file "tocreatefolder" that is empty)

**Comment by akhial** [comment]
Shouldn't you delete it since its your branch? You can then commit again so I can merge...

**Comment by akhial** [comment]
Yaaa mohamed delete ze file 3andek besh nmerji sahitopuuuuuuu

**Pull request closed without merging**
